modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/WonderfulEnchantmentsMod/issues"

[[mods]]
    modId="wonderfulenchantments"
    version="1.7.0"
    displayName="Wonderful Enchantments"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/WonderfulEnchantmentsMod/1.19/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"
    logoFile="logo.png"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Mod adding a lot of new unique enchantments to the game.'''

[[dependencies.wonderfulenchantments]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wonderfulenchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wonderfulenchantments]]
    modId="majruszlib"
    mandatory=true
    versionRange="[2.10.0,3.0.0)"
    ordering="NONE"
    side="BOTH"