modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsEnchantmentsMod/issues"

[[mods]]
    modId="majruszsenchantments"
    version="1.6.3"
    displayName="Majrusz's Enchantments"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsEnchantmentsMod/1.18.X/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"
    logoFile="logo.png"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''Mod that adds plenty of unique and balanced enchantments to the game.'''

[[dependencies.majruszsenchantments]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.69,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsenchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsenchantments]]
    modId="majruszlib"
    mandatory=true
    versionRange="[2.7.3,3.0.0)"
    ordering="NONE"
    side="BOTH"